language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

sudo: false
    
before_install:
 - chmod +x gradlew
 
after_success:
 - ./gradlew proguard
 - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "latest" && curl -F "file=@dist/Own-Programming-Language-Tutorial.jar" http://projects.annimon.com/samples/php/travis/upload.php?mode=ownlang